### PR TITLE
Use fisher compatible directory structure

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by evanlucas** [comment]
Thanks for opening a PR for this. Can you update the README to use the correct path in the installation instructions? I'd also be open to include how to install using fisher in the readme

**Comment by pgilad** [comment]
Will do thanks for considering

**Comment by pgilad** [comment]
Done

**Review by jorgebucaran — APPROVED** [review]

**Comment by pgilad** [comment]
@jorgebucaran I can't merge it

**Comment by jorgebucaran** [comment]
Well, neither can I haha. 😄

**Review by evanlucas — APPROVED** [review]
Thanks!

**Pull request merged**
